# Generated by Django 4.0.5 on 2022-07-11 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('Flight_no', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Flight_model', models.CharField(max_length=30)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('voyid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('From', models.CharField(max_length=30)),
                ('To', models.CharField(max_length=30)),
                ('departure', models.DateTimeField()),
                ('Flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airlines.Flight')),
            ],
        ),
       
    ]
